#!/usr/bin/env bash
sed -n 's/^ *Key(//p' | \
sed '
s/\[//
s/\]//
s/lazy.*, desc/desc/
s/logo, /Super+/
s/alt, /Alt+/
s/"control", /Ctrl+/
s/"shift", /Shift+/
s/"//g
s/, desc=/,/
s/),$//
1iKey,Action
' | \
csvlook