bar:
  height: 26
  location: top
  background: 000000ff

  left:
    - script:
        path: /home/amy/bin/amy-status
        args: [1]
        content: {string: {text: "{wombat}"}}

  right:
    - clock:
        content:
          - string: {text: , font: "Font Awesome 5 Free:style=solid:size=12"}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: "Font Awesome 5 Free:style=solid:size=12"}
          - string: {text: "{time}"}