bar:
  height: 26
  location: top
  spacing: 5
  background: 000000ff

  left:
    # See: man yambar-modules-river
    - river:
        title: {string: { text: "{title}" }}
        all-monitors: true
        content:
          map:
            tag: occupied
            values:
              false: {empty: {}}
              true:
                string:
                  margin: 5
                  text: "{id}: {state}"

  right:
    - network:
        name: wlo2
        content:
          map:
            tag: state
            default: {string: {text: }}
            values:
              down: {string: {text: , foreground: ff0000ff}}
              up:
                map:
                  tag: ipv4
                  default:
                    - string: {text: }
                    - string: {text: "{ssid}"}
                  values:
                    "":
                      - string: {text: }
                      - string: {text: "{ssid}"}
    - clock:
        date-format: "%A, %d %B %Y"
        time-format: "%H:%M"
        content:
          - string: {text: "{date}", right-margin: 5}
          - string: {text: "{time}"}
    - label:
        content:
          string:
            on-click: loginctl poweroff
            text: 