format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#f9ef92"

[character]
success_symbol = "[❯](#9cf992)"
error_symbol = "[❯](#f9929b)"
vicmd_symbol = "[❮](#9cf992)"

[git_branch]
format = "[$branch](#92f9f0)"
style = "c6c9c3"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#92f9f0) ($ahead_behind$stashed)](92f9f0)"
style = "92f9f0"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "c6c9c3"

[cmd_duration]
format = "[$duration]($style) "
style = "#c6c9c3"

[python]
format = "[$virtualenv]($style) "
style = "c6c9c3"
