format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#F1FA8C"

[character]
success_symbol = "[❯](#50FA7B)"
error_symbol = "[❯](#FF5555)"
vicmd_symbol = "[❮](#50FA7B)"

[git_branch]
format = "[$branch](#8BE9FD)"
style = "F8F8F2"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#8BE9FD) ($ahead_behind$stashed)](8BE9FD)"
style = "8BE9FD"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "F8F8F2"

[cmd_duration]
format = "[$duration]($style) "
style = "#F8F8F2"

[python]
format = "[$virtualenv]($style) "
style = "F8F8F2"
